In [1]:
import numpy as np

In [3]:
a = np.empty((3,3))

In [4]:
a

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 7.66789882e-321],
       [1.24561153e-311, 2.00485144e-307, 0.00000000e+000]])

In [5]:
a.fill(1)

In [6]:
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
a.shape

(3, 3)

In [15]:
a[np.newaxis,:]

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [9]:
a.shape

(3, 3)

In [16]:
np.linspace?

Signature:
np.linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
)
Docstring:
Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].

The endpoint of the interval can optionally be excluded.

.. versionchanged:: 1.16.0
    Non-scalar `start` and `stop` are now supported.

.. versionchanged:: 1.20.0
    Values are rounded towards ``-inf`` instead of ``0`` when an
    integer ``dtype`` is specified. The old behavior can
    still be obtained with ``np.linspace(start, stop, num).astype(int)``

Parameters
----------
start : array_like
    The starting value of the sequence.
stop : array_like
    The end value of the sequence, unless `endpoint` is set to False.
    In that case, the sequence consists of all but the last of ``num + 1``
    evenly spaced samples, so that `stop` is excluded.  Note that the step
    size changes when `endpoint` is Fals

In [23]:
def temperature(temperatures):
    result = []
    dtw = 0
    for i,t in enumerate(temperatures):
        if i == len(temperatures)-1:
            result.append(0)
            return result
        for j,tnext in enumerate(temperatures[i+1:]):
            if tnext>t:
                dtw = j+1
                break
        result.append(dtw)
        dtw = 0
    return result

In [24]:
temperature([22,23,21,25,23])

[1, 2, 1, 0, 0]

In [25]:
temperature([21,22,21,22,25,21])

[1, 3, 1, 1, 0, 0]

In [26]:
temperature([-8,-7,-8,-5,-4])

[1, 2, 1, 1, 0]

In [27]:
5//2

2

In [29]:
a = [4,2,3,4]
a.remove(4)
a

[2, 3, 4]

In [30]:
import pandas as pd

In [31]:
a = pd.DataFrame({'a': [1,2,3,4,5], 'b': [7,5,4,3,2]})

In [32]:
a

a  b
0  1  7
1  2  5
2  3  4
3  4  3
4  5  2

In [35]:
a.iloc[:,0]

0    1
1    2
2    3
3    4
4    5
Name: a, dtype: int64

In [36]:
a.reset_index?

Signature:
a.reset_index(
    level: 'Hashable | Sequence[Hashable] | None' = None,
    drop: 'bool' = False,
    inplace: 'bool' = False,
    col_level: 'Hashable' = 0,
    col_fill: 'Hashable' = '',
) -> 'DataFrame | None'
Docstring:
Reset the index, or a level of it.

Reset the index of the DataFrame, and use the default one instead.
If the DataFrame has a MultiIndex, this method can remove one or more
levels.

Parameters
----------
level : int, str, tuple, or list, default None
    Only remove the given levels from the index. Removes all levels by
    default.
drop : bool, default False
    Do not try to insert index into dataframe columns. This resets
    the index to the default integer index.
inplace : bool, default False
    Modify the DataFrame in place (do not create a new object).
col_level : int or str, default 0
    If the columns have multiple levels, determines which level the
    labels are inserted into. By default it is inserted into the first
    level.
col_fill : ob